name: Lua Check

on:
  push:
  pull_request:

jobs:
  lua-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Lua Language Server
        run: sudo snap install lua-language-server --classic

      - name: Run Lua Language Server
        run: lua-language-server --check_format=pretty --check="${{ github.workspace }}" --checklevel=Hint